### PR TITLE
fix(Hybrid Map): added phoneNumber to listing to render Phone CTA Button

### PR DESCRIPTION
**Pull request by grenti**
affects: @rentpath/react-ui-ag, @rentpath/react-ui-core

(Card)[https://rentpath.leankit.com/card/613135571]
- Added phoneNumber data to listing
- Updated Button component to take in a nodeType
- updated renderCTAButton method

### CODE REVIEW

**Comment by yasabere** [comment]
LGTM 👍

**Comment by grenti** [comment]
Please note that this is a hack. I would rather put the CTA button data and rendering info inside the listing prop object so each listing can control whether they render a CTA button or not but in the interest of time, we added this data to help generate the phone CTA button (which really is an anchor tag not a button)

**Comment by paudyalhari** [comment]
👍

**Comment by bethstevic** [comment]
Looks good 👍

**Pull request merged**
