### PR TITLE
fix(ListingCarousel): increases debounce time in ListingCarousel

### PR DESCRIPTION
**Pull request by yasabere**
affects: @rentpath/react-ui-ag

Increases the debounce time in ListingCarousel

### CODE REVIEW

**Comment by bethstevic** [comment]
Looks good to me 👍

**Comment by nray621** [comment]
I was going to ask if the debounce time was increased too much, but then I realized if you're trying to tap twice in 1.2 seconds you need to chill

**Comment by nray621** [comment]
LGTM 👍

**Comment by tadjohnston** [comment]
Please provide an explanation as to why the increase and a corresponding ticket.

**Pull request closed without merging**
